// Generated from C:/CodexProj/*.mhtml item cards and supplemented from verified wiki.gg item tables.
// Top-level card counts were validated against the item count rendered on each saved page.
// Satanic: 402
// Set: 254
// Heroic: 192
// Angelic: 30
// Unholy: 19
// Runeword: 92
// Normalized item names are used so punctuation and diacritics do not affect lookup.
type KnownItemRarity = "Satanic" | "Set" | "Angelic" | "Heroic" | "Unholy" | "Runeword";

const ITEM_RARITY_BY_NAME: Record<string, KnownItemRarity> = {
  "abomination's brain": "Set",
  "abomination's eye": "Set",
  "abomination's gut ripper": "Satanic",
  "abomination's heart": "Set",
  "absolute zero": "Unholy",
  "adamant roamers": "Heroic",
  "adventurer's quiver": "Satanic",
  "aegisweave robes": "Satanic",
  "aetherflow treads": "Satanic",
  "aetherweaver's veil": "Satanic",
  "aimbot.exe": "Satanic",
  "air melon": "Angelic",
  "ak-47": "Heroic",
  "ali's boxing gloves": "Heroic",
  "all seeing eye": "Satanic",
  "amethyst knight's amulet": "Satanic",
  "amulet of colosseum": "Heroic",
  "ancient aegis": "Heroic",
  "ancient avenger": "Satanic",
  "ancient mucus": "Satanic",
  "ancient sun beacon": "Satanic",
  "angel": "Set",
  "angul auxana": "Runeword",
  "annihilator": "Unholy",
  "anubis oculus": "Set",
  "anubis torso": "Set",
  "anubis' ankh charm": "Satanic",
  "anubis' mighty hands": "Set",
  "apex striker's ring": "Satanic",
  "apocalypto": "Satanic",
  "apple of evolution": "Satanic",
  "arachno phobia": "Heroic",
  "arc's sigil": "Set",
  "arc's walkers": "Set",
  "arcana eye": "Satanic",
  "arcane bastion": "Runeword",
  "arcane gladiator's armor": "Satanic",
  "arcane pumpkin": "Unholy",
  "arcane robes of authority": "Satanic",
  "arcane slayer's talisman": "Satanic",
  "arcanis": "Heroic",
  "arcanist's wrath": "Heroic",
  "arcanum": "Runeword",
  "arcanum asphyxiators": "Heroic",
  "arch angel's phase blade": "Heroic",
  "arch wizard's silk boots": "Satanic",
  "archangel staff": "Satanic",
  "archer's story": "Satanic",
  "archmagus glyphward": "Satanic",
  "arena master's marchers": "Satanic",
  "arrow of niflheim": "Heroic",
  "arrow of zamjo": "Heroic",
  "ascendancy": "Runeword",
  "ashbringer": "Satanic",
  "ashen belt": "Satanic",
  "assassin's belt": "Satanic",
  "assassin's hood": "Satanic",
  "astral projector": "Heroic",
  "astral roamers": "Heroic",
  "astrope's signed of blessing": "Satanic",
  "astropos": "Runeword",
  "atonement": "Runeword",
  "aurelion fury": "Angelic",
  "aurora's might": "Runeword",
  "azazel's despair": "Heroic",
  "aztec coin": "Satanic",
  "aztec crown": "Set",
  "aztec devil": "Set",
  "aztec necklace": "Set",
  "aztec ward": "Set",
  "azure's wrath": "Satanic",
  "baby log necklace": "Satanic",
  "babylon's fall": "Runeword",
  "bag of unknown riches": "Satanic",
  "bandit lord's shroud": "Satanic",
  "barrel of explosives": "Set",
  "battle caster's gauntlets": "Satanic",
  "battle mage's shield": "Satanic",
  "battle mage's wand": "Satanic",
  "battle worn boots": "Set",
  "battle worn gauntlets": "Set",
  "battle worn visor": "Set",
  "battlemagi's rampart": "Satanic",
  "beacon of shadows": "Heroic",
  "beetle of life": "Satanic",
  "behemoth's damascus body": "Satanic",
  "belt of infinite wealth": "Heroic",
  "belt of skulls": "Heroic",
  "belt of war": "Satanic",
  "big joe": "Runeword",
  "black knight's carapace": "Satanic",
  "blessed defender": "Satanic",
  "blitzkrieg": "Runeword",
  "blood moon crescent": "Heroic",
  "blood of abaddon": "Heroic",
  "blood of spartan": "Satanic",
  "blood-letter's crown": "Set",
  "blood-letter's plate body": "Set",
  "blood-letter's plated boots": "Set",
  "blood-letter's plated gauntlet": "Set",
  "bloodthirster's warhelm": "Satanic",
  "bob's grenade": "Set",
  "bob's piece of plywood": "Satanic",
  "bone conjurer's grips": "Set",
  "bone conjurer's marchers": "Set",
  "bone conjurer's mask": "Set",
  "bone conjurer's trophy": "Set",
  "bonetti's rapier": "Heroic",
  "book of cold death": "Heroic",
  "book of revelations": "Satanic",
  "bottle of radogate": "Satanic",
  "bottle of sake": "Satanic",
  "boots of blood": "Satanic",
  "boots of wild": "Set",
  "brawler's fighting mitts": "Heroic",
  "breath of the damned": "Runeword",
  "brilliance": "Runeword",
  "brimskull trident": "Heroic",
  "bristle": "Runeword",
  "bronze legion girdle": "Satanic",
  "brutal roamers": "Heroic",
  "brutality": "Runeword",
  "brute's cord": "Satanic",
  "bubonic plague's pledge": "Runeword",
  "bull's eye": "Set",
  "buriza-ko-nu": "Satanic",
  "burning gaze": "Satanic",
  "butcher's apron": "Set",
  "butcher's belt": "Set",
  "butcher's hood": "Set",
  "caffeinated coffee container": "Satanic",
  "candy shredder": "Heroic",
  "cane of creation": "Heroic",
  "cane of the tundra": "Satanic",
  "canopic jar of blood": "Set",
  "carnage": "Runeword",
  "catastrophe": "Runeword",
  "celestial's authority": "Heroic",
  "celestus": "Runeword",
  "ceremonial dagger": "Satanic",
  "champion's fighting gloves": "Set",
  "champion's flag lance": "Set",
  "champion's medal of valor": "Set",
  "champion's signet": "Set",
  "chaos gemstone": "Heroic",
  "chaoswalkers": "Heroic",
  "charcoal memento": "Satanic",
  "chestplate of fire": "Set",
  "chilling roamers": "Heroic",
  "chills of war": "Satanic",
  "chimera": "Runeword",
  "chronobreakers": "Heroic",
  "chronomancer's curio of time": "Set",
  "chronomancer's observance": "Set",
  "chronomancer's omnipotence": "Set",
  "cingulum of shifting destiny": "Satanic",
  "circle of nature": "Satanic",
  "clafaxier": "Satanic",
  "clafaxier's legacy": "Heroic",
  "clan leader's pride": "Satanic",
  "claw of the bloodthirsty": "Satanic",
  "claw of the hunter": "Satanic",
  "cobra blood vial": "Satanic",
  "cocoon of the berserker": "Satanic",
  "cold giant's charm": "Satanic",
  "coldfire amulet": "Satanic",
  "coldsnap insignia": "Satanic",
  "colossus": "Runeword",
  "colossus circle of vitality": "Satanic",
  "combat duty belt": "Satanic",
  "commander's sentry blaster": "Angelic",
  "commander's sash": "Satanic",
  "compass of wealth": "Heroic",
  "conjurer mitts": "Satanic",
  "conquest": "Runeword",
  "crackling thunder": "Heroic",
  "crematorium's pledge": "Runeword",
  "crow's feather": "Satanic",
  "crow's whisper": "Heroic",
  "crown of doom": "Heroic",
  "crown of midnight": "Satanic",
  "crown of the antichrist": "Runeword",
  "crown of the north": "Satanic",
  "crusader halberd": "Satanic",
  "crushfleet": "Runeword",
  "crystal belt": "Satanic",
  "crystal cane of ice": "Satanic",
  "crystal infused axe": "Satanic",
  "crystal infused javelin": "Satanic",
  "crystal infused pistol": "Satanic",
  "crystal infused shield": "Satanic",
  "crystal infused sword": "Satanic",
  "crystal infused wand": "Satanic",
  "cuirass of blood": "Satanic",
  "curse": "Runeword",
  "cursed artifact": "Satanic",
  "cursed gyroscope": "Satanic",
  "daisy": "Set",
  "damien's cage": "Set",
  "damien's corrupted head": "Heroic",
  "damien's head": "Set",
  "damien's soulstone": "Set",
  "dante's boots": "Set",
  "dante's demon blade": "Set",
  "dante's jacket": "Set",
  "dante's mitts": "Set",
  "dark knight's lance": "Heroic",
  "dark lord's sigil": "Satanic",
  "dark vial of corrosion": "Satanic",
  "darkhide boots": "Satanic",
  "darkness": "Satanic",
  "darkwood defender": "Satanic",
  "death knight's gauntlets": "Heroic",
  "death knight's visage": "Satanic",
  "death lord's bone armor": "Set",
  "death lord's crown": "Set",
  "death lord's marchers": "Set",
  "death lord's zombie head": "Set",
  "death's grasp": "Set",
  "death's mirror": "Satanic",
  "death's scythe": "Set",
  "deathquill": "Heroic",
  "deep chilled marchers": "Satanic",
  "deep sea glaive": "Satanic",
  "defender's justice": "Heroic",
  "delirium tremens": "Runeword",
  "demon": "Set",
  "demon blood flask": "Satanic",
  "demon eye ring": "Satanic",
  "demon warlord's helm": "Satanic",
  "demon's mirror": "Heroic",
  "demon's ribcage": "Set",
  "demonfire accelerators": "Unholy",
  "demonweaver's heralds": "Satanic",
  "den glider in": "Satanic",
  "desert's storm": "Heroic",
  "desert's wrath": "Runeword",
  "destroyer's end": "Heroic",
  "destroyers end": "Heroic",
  "deus ex machina": "Runeword",
  "devil's cocoon": "Satanic",
  "devil's gem": "Set",
  "devil's grasp": "Set",
  "devil's pact": "Unholy",
  "diablo": "Heroic",
  "dibbik box": "Set",
  "disaster": "Runeword",
  "divine contemplation": "Runeword",
  "divinity": "Runeword",
  "doctor's grasp": "Set",
  "doctor's mask in a jar": "Set",
  "doctor's potion": "Set",
  "doctor's visage": "Set",
  "doom cutter": "Satanic",
  "doomsaw": "Satanic",
  "doomweed vial": "Satanic",
  "doublesaw 4000": "Satanic",
  "dracula's demise": "Heroic",
  "dragon knight's flail": "Satanic",
  "dragon knight's helmet": "Heroic",
  "dragon knight's vanguard": "Heroic",
  "dragon's blessing": "Heroic",
  "dragon's breath": "Satanic",
  "dragon's eye": "Heroic",
  "dragon's heart": "Heroic",
  "dragonsteel ring": "Satanic",
  "dreadnought": "Heroic",
  "eagerblade's tooth": "Satanic",
  "eagle's claw": "Heroic",
  "earth goliath's protection": "Satanic",
  "earth melon": "Angelic",
  "earth shaper's belt": "Set",
  "earth shaper's body": "Set",
  "earth shaper's boots": "Set",
  "earth shaper's talons": "Set",
  "eden's harvester": "Heroic",
  "einar's horned helmet": "Set",
  "einar's icy stride": "Set",
  "einar's padded gauntlets": "Set",
  "einar's plated armor": "Set",
  "el patron's madness": "Unholy",
  "elder's heart": "Satanic",
  "electro": "Satanic",
  "elixir of death": "Satanic",
  "elixir of unworldly cognition": "Satanic",
  "elemental claws": "Satanic",
  "elementalist's silk shroud": "Satanic",
  "empty bottle of vodka": "Satanic",
  "elven grace": "Satanic",
  "emblem of the daemon": "Heroic",
  "empire's military plate": "Satanic",
  "engineer's master pendant": "Set",
  "engineer's mini drone": "Set",
  "engineer's plated vest": "Set",
  "engineer's toolbelt": "Set",
  "enigma's riftwalkers": "Satanic",
  "ent's blessing": "Runeword",
  "epilogue": "Runeword",
  "eternal death": "Heroic",
  "eternal glaive": "Satanic",
  "eternity": "Heroic",
  "etherwalk": "Runeword",
  "executioner's cocoon": "Heroic",
  "executioner's headplate": "Satanic",
  "exiled pagan's mantle": "Satanic",
  "eye of horus": "Satanic",
  "eye of rakhul": "Heroic",
  "eye of skadi": "Satanic",
  "f4-tactical rifle": "Satanic",
  "face of existence": "Heroic",
  "fenrir's bloodfang": "Heroic",
  "feral": "Runeword",
  "fighter magi's grips": "Heroic",
  "finger of despair": "Heroic",
  "fire melon": "Angelic",
  "flame diviner's cord": "Set",
  "flame diviner's refuge": "Set",
  "flame diviner's sanctum": "Set",
  "flame diviner's ward": "Set",
  "flame god's helmet": "Satanic",
  "flame of the phoenix": "Satanic",
  "flamebringer": "Satanic",
  "flamecannon": "Satanic",
  "flaming coin": "Set",
  "flaming marchers": "Set",
  "flesh ripper": "Runeword",
  "flowing agony": "Runeword",
  "flowing sands": "Runeword",
  "fog": "Runeword",
  "force": "Runeword",
  "forking bolts": "Unholy",
  "fortress": "Runeword",
  "foxweave belt": "Satanic",
  "fractal of existence": "Heroic",
  "fred": "Satanic",
  "freljord": "Runeword",
  "freya's frozen buckle": "Heroic",
  "frostbitten necrosis": "Heroic",
  "frozen carver": "Satanic",
  "frozen marchers": "Satanic",
  "fulgurite": "Heroic",
  "fumacinha's favela flipflop": "Heroic",
  "fury of tarethiel": "Angelic",
  "gabriel's brimmed fedora": "Set",
  "gabriel's broken resolve": "Heroic",
  "gabriel's broken wings": "Heroic",
  "gabriel's dauntless vision": "Heroic",
  "gabriel's leather trench coat": "Set",
  "gabriel's unholy oath": "Heroic",
  "gambler's demise": "Satanic",
  "gargantuan's soul": "Satanic",
  "gas canister": "Heroic",
  "gaze of the oblivion": "Heroic",
  "gaze of the void": "Satanic",
  "gem encrusted tower": "Satanic",
  "gem king's cleaver": "Heroic",
  "gem king's garb": "Heroic",
  "genji's battle armor": "Set",
  "genji's battle helmet": "Set",
  "genji's sword of fate": "Set",
  "ghost": "Runeword",
  "giant thorned lizard skin": "Satanic",
  "giant's band of strength": "Heroic",
  "girdle of eternal war": "Heroic",
  "girdle of resilience": "Satanic",
  "glacial gladiator's armor": "Satanic",
  "glacier talons": "Heroic",
  "gladiator king's belt": "Heroic",
  "gladiator's battle sandals": "Set",
  "gladiator's demise": "Satanic",
  "gladiator's dice": "Heroic",
  "gladiator's skullcrusher": "Satanic",
  "gladiator's skullet": "Set",
  "gladiator's wall": "Set",
  "gladiator's wrecking ball": "Set",
  "gladstone goose's jacket": "Runeword",
  "glimmerfury": "Satanic",
  "glock 22": "Unholy",
  "gloves of wilderness": "Set",
  "glowstick estoc": "Heroic",
  "ghostly potion": "Satanic",
  "goburin's head": "Unholy",
  "god's benevolence": "Satanic",
  "godfather": "Satanic",
  "gold inlaid mysterious potion": "Heroic",
  "golden god's gladius": "Satanic",
  "grand arch wizard s mantle": "Unholy",
  "grand wizard's silk shoes": "Satanic",
  "grandwizard's robe": "Satanic",
  "grasp of the phoenix": "Heroic",
  "graxy's mom lure": "Heroic",
  "grief": "Runeword",
  "grimbone's marchers": "Heroic",
  "grimbone's ribcage": "Heroic",
  "grimbone's scythe": "Heroic",
  "grimbone's visage": "Heroic",
  "grimwalkers": "Runeword",
  "gryphon's claw": "Heroic",
  "guardian's waistband": "Satanic",
  "guise of the dead": "Satanic",
  "gurag's heart charm": "Set",
  "gurag's pebble": "Set",
  "gurag's stone crusher": "Set",
  "gut's bfs": "Satanic",
  "gut's hfs": "Satanic",
  "hands of flame": "Set",
  "hanzo's flaming katana": "Satanic",
  "hardened steel defender": "Satanic",
  "harlequinn's crest": "Satanic",
  "harlequinn's veil": "Heroic",
  "harvester": "Runeword",
  "hatshepsut's girdle": "Satanic",
  "havoc": "Runeword",
  "hazmat suit": "Satanic",
  "headsman's bloodthirster": "Heroic",
  "heart of agony": "Set",
  "heaven's champion": "Satanic",
  "heaven's might": "Satanic",
  "heavy duty": "Satanic",
  "hellfire cuirass": "Satanic",
  "hellfire halo": "Heroic",
  "hello its me, steve!": "Set",
  "hellspawn eradicator": "Satanic",
  "hellspawn's curse": "Satanic",
  "helm of dominator": "Satanic",
  "hemorrhage": "Satanic",
  "hermes boots": "Satanic",
  "high demon's necklace": "Satanic",
  "high roller's deathcrown": "Heroic",
  "hiyoki's vorpal katana": "Satanic",
  "holy warrior's phase blade": "Satanic",
  "hydrangea": "Runeword",
  "hypothermia": "Heroic",
  "ice howl's cuirass": "Satanic",
  "ice king's crown": "Satanic",
  "ice queen's cestus": "Satanic",
  "icy crusher": "Satanic",
  "icy shank": "Satanic",
  "imbued mage gloves": "Satanic",
  "imperial glaive": "Satanic",
  "inferno slayer": "Satanic",
  "inner fire": "Runeword",
  "insignia of the burning legion": "Satanic",
  "insignia of the hunter": "Set",
  "iron giants shield": "Satanic",
  "iron ring of prometheus": "Satanic",
  "ironclad protector": "Satanic",
  "isarius ironthorn breastplate": "Heroic",
  "jack": "Satanic",
  "jack's pumpkin spice": "Satanic",
  "jade warrior's gladius": "Satanic",
  "jousting lance": "Satanic",
  "juda's broken halo": "Satanic",
  "judge": "Runeword",
  "judge, jury & executioner": "Satanic",
  "juggernaut's emblem": "Set",
  "juggernaut's glorious plate": "Set",
  "juggernaut's siege helm": "Set",
  "juggernaut's victory marchers": "Set",
  "justice": "Runeword",
  "justiciar's thunder armor": "Set",
  "justiciar's thunder boots": "Set",
  "justiciar's thunder sash": "Set",
  "justiciar's thunder wall": "Set",
  "kallik's fury": "Satanic",
  "khodo's wedding band": "Satanic",
  "king's tower shield": "Satanic",
  "knight captain's helmet": "Satanic",
  "knight's girdle": "Satanic",
  "kogarasumaru": "Runeword",
  "komodo's bloodstrap": "Heroic",
  "komodos bloodstrap": "Heroic",
  "lancer's chestplate": "Set",
  "lancer's glory": "Set",
  "lancer's wall": "Satanic",
  "lancers gauntlets": "Set",
  "lava king's lost mask": "Heroic",
  "lava treaders": "Satanic",
  "leather muscle breastplate": "Satanic",
  "legionnaire": "Runeword",
  "leprechauns greed": "Satanic",
  "leviathan's carcass": "Satanic",
  "lich sash": "Satanic",
  "lichbane": "Satanic",
  "lifeblood infuser": "Satanic",
  "lifeward gauntlets": "Satanic",
  "light bringer's mark": "Satanic",
  "lightforge": "Runeword",
  "lilith's scorn": "Unholy",
  "lilith's wrath": "Unholy",
  "liquor holster": "Angelic",
  "loaded dice": "Heroic",
  "lost dieties authority": "Satanic",
  "lost dimension": "Runeword",
  "lost master's gauntlets": "Set",
  "lost master's marchers": "Set",
  "lost master's platemail": "Set",
  "lost master's vision": "Set",
  "lost wizard's barrier": "Satanic",
  "luci's day": "Heroic",
  "lucifer's crown": "Angelic",
  "lumberjack's chainsaw": "Set",
  "lumberjack's forestry boots": "Set",
  "lumberjack's safety gloves": "Set",
  "lumberjack's safety helm": "Set",
  "lunar prophet's band": "Set",
  "lunar prophet's girdle": "Set",
  "lunar prophet's tiara": "Set",
  "lunar prophet's walkers": "Set",
  "mage's starshroud": "Satanic",
  "maggot eye elixir": "Satanic",
  "magic-imbued frozen plate": "Satanic",
  "magister's robe": "Satanic",
  "magiward battlegear": "Satanic",
  "magma gladiator's armor": "Satanic",
  "majorie's belt": "Angelic",
  "malice": "Runeword",
  "mana bender's will": "Heroic",
  "mana-woven walkers": "Satanic",
  "manafunneler's conjurer": "Heroic",
  "manahungerers": "Heroic",
  "marcher's of hatred": "Unholy",
  "marine's buddy": "Satanic",
  "mark of ferocity": "Satanic",
  "mark of the black knight": "Satanic",
  "marksman's hunting bow": "Set",
  "marksman's hunting gloves": "Set",
  "marksman's hunting shroud": "Set",
  "marksman's quiver": "Set",
  "marsh shroud": "Satanic",
  "martyr": "Runeword",
  "masamune": "Set",
  "mask of the beyond": "Satanic",
  "mask of the celestial": "Angelic",
  "master's magnum": "Heroic",
  "mayhem": "Runeword",
  "merlock's halo": "Satanic",
  "metal vocalist's fame": "Set",
  "metal vocalist's leather mask": "Set",
  "metal vocalist's pentagram": "Set",
  "metal vocalist's war boots": "Set",
  "metal vocalist's warlock": "Set",
  "mevius' mighty gauntlets": "Set",
  "mevius' mighty helmet": "Set",
  "mevius' mighty marchers": "Set",
  "mevius' mighty plate": "Set",
  "midas' hands": "Heroic",
  "mimir's corrupted axe": "Satanic",
  "mirage": "Runeword",
  "mirror of flesh": "Satanic",
  "mjolner": "Runeword",
  "molten boots": "Satanic",
  "molten dagger": "Satanic",
  "molten hammer": "Satanic",
  "molten paw": "Satanic",
  "molten ring": "Satanic",
  "molten steel cataphract": "Satanic",
  "molten sword": "Satanic",
  "moltening": "Runeword",
  "monkeyskin belt": "Satanic",
  "monsoon": "Heroic",
  "moonshard": "Satanic",
  "mos'arathim marchers": "Satanic",
  "mos'arathim's kicks": "Satanic",
  "muramasa": "Set",
  "muspelheim guardian's scorched plate": "Heroic",
  "mysterious monkey paw": "Set",
  "mystery card": "Satanic",
  "mystic soles": "Satanic",
  "mystify": "Runeword",
  "mystique allure": "Satanic",
  "necrobutcher's curse": "Satanic",
  "necrocaller's grips": "Heroic",
  "nightmare slasher": "Satanic",
  "nikita's kj-33 helmet": "Heroic",
  "ninja tabi": "Runeword",
  "nirvana": "Runeword",
  "nobunaga's battle cuirass": "Set",
  "nobunaga's battle helmet": "Set",
  "nobunaga's battle slicer": "Set",
  "nobunaga's warrior spirit": "Set",
  "nomad's battlerobe": "Set",
  "nomad's sand bandana": "Set",
  "nomad's sand mitts": "Set",
  "nomad's sandslicer": "Set",
  "novice's tower": "Satanic",
  "noxious hunter's reward": "Heroic",
  "oculus of ages": "Heroic",
  "odin's battle axe": "Satanic",
  "odin's battle spear": "Satanic",
  "odin's battlearmor": "Set",
  "odin's eternal visage": "Set",
  "onslaught stompers": "Satanic",
  "onyx slayer's band": "Satanic",
  "orange grayon": "Satanic",
  "orbital loop": "Satanic",
  "overloaded dice": "Unholy",
  "pagan god's blasphemy": "Heroic",
  "pandemic shield": "Satanic",
  "paradox": "Runeword",
  "pearlescent dream": "Heroic",
  "peg leg": "Unholy",
  "pendant of eternity": "Heroic",
  "perdition": "Runeword",
  "philosopher's stone": "Heroic",
  "pillar of niflheim": "Satanic",
  "pirate captain's boots": "Set",
  "pirate captain's flag": "Set",
  "pirate captain's hat": "Set",
  "pirate captain's shirt": "Set",
  "pit fighter's band shirt": "Set",
  "pit fighter's bone crushers": "Set",
  "pit fighter's brutalizer": "Set",
  "pit fighter's carnage": "Set",
  "pit fighter's skullcracker": "Set",
  "pit lord's vanquisher": "Satanic",
  "pit ravager's cetratus": "Heroic",
  "pitfiend's thorn": "Satanic",
  "pitfighter's razor belt": "Satanic",
  "pla-yer's choice": "Satanic",
  "plague bringer's touch": "Heroic",
  "plague shot": "Satanic",
  "plated crimson defenders": "Satanic",
  "plunderer's deck marchers": "Set",
  "plunderer's gunpowder bag": "Set",
  "plunderer's jacket": "Set",
  "plunderer's spy glass": "Set",
  "poison ivy": "Satanic",
  "poseidon's might": "Satanic",
  "power of void": "Satanic",
  "potency": "Runeword",
  "praetorian blood": "Satanic",
  "preacher": "Runeword",
  "prismatic potion": "Satanic",
  "prophet's branch": "Set",
  "prophet's foliage": "Set",
  "prophet's pinecone": "Set",
  "prophet's shroud": "Set",
  "protein shake": "Satanic",
  "pyramid pendant": "Satanic",
  "quickening zephyr": "Heroic",
  "quickstep": "Runeword",
  "ra's band": "Satanic",
  "radbull": "Satanic",
  "raider's torch": "Satanic",
  "rainbow": "Runeword",
  "raise of the dead": "Satanic",
  "rakhul's legion crusher": "Heroic",
  "rakhul's ritual band": "Heroic",
  "rakhul's stone hands": "Heroic",
  "rapidcaster mitts": "Satanic",
  "rapidshell medallion": "Satanic",
  "ravager": "Runeword",
  "raven's claw": "Satanic",
  "razor knuckles": "Satanic",
  "reaper's hood": "Set",
  "reaver's headplate": "Satanic",
  "recurving corrosion": "Heroic",
  "redneck's cap": "Set",
  "redneck's keychain": "Set",
  "redneck's shirt": "Set",
  "redneck's working boots": "Set",
  "rendguard of carnage": "Satanic",
  "revelation": "Runeword",
  "revenant's lasher": "Satanic",
  "reverse card": "Angelic",
  "rift commander's axe": "Satanic",
  "rift eye": "Satanic",
  "rift vectors": "Heroic",
  "rift warrior's skull": "Satanic",
  "riftmaster's dirge": "Heroic",
  "rimskin assassins": "Heroic",
  "ring of tallus": "Satanic",
  "ring of the cowraven": "Satanic",
  "ritual pendant": "Satanic",
  "rocket boots": "Satanic",
  "rotten pumpkin": "Unholy",
  "royal decapitator": "Satanic",
  "rt xqc-4910": "Satanic",
  "rugal's sash of undertaking": "Satanic",
  "runemaster's mantle": "Satanic",
  "runemaster's waistwrap": "Satanic",
  "runescribe's striders": "Satanic",
  "rusted spiked shield": "Satanic",
  "sacred aegis": "Set",
  "sacred marchers": "Set",
  "sacred owl": "Set",
  "sacred pendant": "Set",
  "sacred robe": "Set",
  "sacred whip": "Satanic",
  "sahkopuimuri": "Heroic",
  "sand crusader's scimitar": "Satanic",
  "sand dagger": "Satanic",
  "sand king's scarab": "Satanic",
  "sand manipulator's authority": "Set",
  "sand manipulator's kalasiris": "Set",
  "sand manipulator's mask": "Set",
  "sand traveler's guise": "Satanic",
  "sandmagi's sash": "Satanic",
  "sands of time": "Satanic",
  "sanguine blade": "Satanic",
  "sanguine bloodstone": "Satanic",
  "sarcaster's coffee mug": "Satanic",
  "sarcasters coffee mug": "Satanic",
  "sash of eternal hatred": "Heroic",
  "sash of the magi": "Satanic",
  "sassy's dislocated foot": "Satanic",
  "satan's chalice": "Satanic",
  "satan's cuirass": "Set",
  "satan's molten steps": "Set",
  "satan's precious": "Set",
  "satan's unholy bible": "Satanic",
  "satanic eye": "Satanic",
  "sawgun": "Satanic",
  "scarred battle darts": "Heroic",
  "scholar": "Runeword",
  "scorching roamers": "Heroic",
  "scourge gladiator's armor": "Satanic",
  "scourge loop": "Heroic",
  "scout's medal of honor": "Satanic",
  "scuttle crab gauntlets": "Satanic",
  "sentinel's headguard": "Satanic",
  "serpent's embrace": "Heroic",
  "serpent's tooth": "Heroic",
  "serpentine necklace": "Satanic",
  "set's lightning sash": "Heroic",
  "shade of sand": "Satanic",
  "shadow": "Runeword",
  "shadow beacon": "Heroic",
  "shadow buckler": "Satanic",
  "shadow carver": "Heroic",
  "shadow lantern": "Heroic",
  "shadow occultist's wraps": "Heroic",
  "shadow's grasp": "Satanic",
  "shadowfury": "Heroic",
  "sharpshooter's cloak": "Heroic",
  "shattered dimensions": "Satanic",
  "sheep king's crown": "Set",
  "sheep king's hide": "Set",
  "sheep king's wool": "Set",
  "shelter": "Runeword",
  "shield bearer's crown": "Set",
  "shield bearer's greaves": "Set",
  "shield bearer's plated armor": "Set",
  "shield bearer's wall": "Set",
  "shield of shattered elements": "Satanic",
  "shield of the abyss": "Heroic",
  "shining pearl": "Satanic",
  "shinobi's deadwraps": "Satanic",
  "shishkebab": "Heroic",
  "shroud of elements": "Runeword",
  "shroud of enigma": "Runeword",
  "shrunken head": "Satanic",
  "sidewinder": "Heroic",
  "siege breakers": "Satanic",
  "sight of the gods": "Heroic",
  "signet of bifrost": "Satanic",
  "signet of corruption": "Heroic",
  "signet of harbringer": "Heroic",
  "signet of kadosh": "Heroic",
  "signet of shadows": "Heroic",
  "skinwalker's claw": "Set",
  "skinwalker's mantle": "Set",
  "skinwalker's paw": "Set",
  "skinwalker's sigil": "Set",
  "sky crusader helm": "Satanic",
  "skysong": "Runeword",
  "sleight": "Runeword",
  "sniper's scope": "Set",
  "sobek's fall": "Heroic",
  "solar charm": "Satanic",
  "solar magister's sash": "Satanic",
  "solar prophet's crown": "Set",
  "solar prophet's robes": "Set",
  "solar prophet's signet": "Set",
  "solar prophet's tablet": "Set",
  "sonicstep": "Runeword",
  "sorcerer's surge grips": "Satanic",
  "soul collector": "Unholy",
  "soul funneling loop": "Satanic",
  "soulburn belt": "Heroic",
  "soulflaming marchers": "Heroic",
  "soulforged ring": "Heroic",
  "soulreplenish pendant": "Satanic",
  "sovereignty": "Runeword",
  "sowyer's javelin of devastation": "Heroic",
  "spell eater": "Heroic",
  "spellbinder's magebarrier": "Satanic",
  "spellshard": "Satanic",
  "spellweavers": "Heroic",
  "spiked greaves": "Satanic",
  "spine trophy": "Satanic",
  "spirit pendant": "Set",
  "spirit urn": "Satanic",
  "spirit walker's guide": "Satanic",
  "spiritus": "Satanic",
  "st. aaron's eternal rage": "Angelic",
  "st. ahto's diamond hands": "Angelic",
  "st. brooks elementium pistol": "Angelic",
  "st. amitiel's truth": "Angelic",
  "st. draxis longsaw": "Angelic",
  "st. draxis' pigstick": "Angelic",
  "st. gabriel's retribution": "Angelic",
  "st. hallgar's bloodforged aegis": "Angelic",
  "st. houdeanii's tiny fire rod": "Angelic",
  "st. jupe's plate of command": "Angelic",
  "st. mika's zweihander": "Angelic",
  "st. neri's rainbow lance": "Angelic",
  "st. nimo's lightbringer": "Angelic",
  "st. rexis sundering axe": "Angelic",
  "st. soloyolo's holy bow": "Angelic",
  "st. tomi's vibrant aura": "Angelic",
  "staff of nether flame": "Satanic",
  "stalwart sabatons": "Satanic",
  "steadfast marchers": "Satanic",
  "steampowered flamewalkers": "Heroic",
  "steve's bang": "Set",
  "steve's mighty sword": "Set",
  "steve's necklace": "Set",
  "steve's punchbow": "Set",
  "steve's wand of fortune": "Set",
  "stofflix cooking cleaver": "Unholy",
  "stone of archaeology": "Satanic",
  "stone of premonition": "Heroic",
  "stoneplate of corruption": "Heroic",
  "storm fury": "Angelic",
  "storm gladiator's wall": "Satanic",
  "storm in a vial": "Heroic",
  "storm katana": "Satanic",
  "storm pendant": "Satanic",
  "storm's dawn": "Satanic",
  "stormloop": "Heroic",
  "stormslayer": "Unholy",
  "stranded boot": "Heroic",
  "sun wukong's belt": "Satanic",
  "sundial of ancient worlds": "Set",
  "sung lee's destroyer flail": "Heroic",
  "sung lee's flask of carnage": "Heroic",
  "sung lee's unleashed rage": "Heroic",
  "suomi finland perkele": "Heroic",
  "suomi finland suatana": "Satanic",
  "surgical mask": "Satanic",
  "surstromming": "Satanic",
  "swiftsoul band": "Satanic",
  "tablet of awakening": "Heroic",
  "tactical flak jacket": "Set",
  "tal's deathskull": "Set",
  "tal's pendant": "Set",
  "talons of wisdom": "Satanic",
  "tarek's tradeoff": "Satanic",
  "tarethiel's ancient wisdom": "Heroic",
  "tarethiel's fall": "Heroic",
  "tayrel's chestplate": "Angelic",
  "tectonic frequency": "Satanic",
  "tectonic grips": "Heroic",
  "telescope": "Set",
  "templar's faith": "Satanic",
  "tenebris' grievance": "Satanic",
  "tether of anguish": "Satanic",
  "the absence of constraint": "Heroic",
  "the annihilator": "Satanic",
  "the bucket": "Satanic",
  "the colossal avenger": "Heroic",
  "the curator of secrets": "Satanic",
  "the dawn bringer": "Angelic",
  "the detonator": "Set",
  "the downfall of felps": "Heroic",
  "the event horizon": "Heroic",
  "the eye of tarethiel": "Heroic",
  "the faceless priest": "Satanic",
  "the grand champion": "Satanic",
  "the hope ender": "Heroic",
  "the iris": "Satanic",
  "the light of dawn": "Heroic",
  "the templar": "Satanic",
  "the undying": "Satanic",
  "thinking cap": "Runeword",
  "thor's battle cap": "Set",
  "thor's battle gloves": "Set",
  "thor's battle sword": "Set",
  "thor's chest armor": "Set",
  "thorn of helheim": "Set",
  "thorn of noxus": "Heroic",
  "thorned wristguards": "Satanic",
  "thoth's agony": "Heroic",
  "throat cutters": "Satanic",
  "thunder caller's robe": "Set",
  "thunder caller's sash": "Set",
  "thunder caller's treads": "Set",
  "thunder caller's veil": "Set",
  "thunder dagger": "Satanic",
  "thunder gladiator's armor": "Satanic",
  "thunder guardian's plate": "Heroic",
  "thunder lord's aegis": "Satanic",
  "thunder roamers": "Heroic",
  "thunderburn aegis": "Satanic",
  "thunderstone amulet": "Satanic",
  "thunderstruck deflector": "Satanic",
  "tiny planet": "Set",
  "titan's staticguards": "Satanic",
  "tombstone": "Heroic",
  "torch of shadows": "Heroic",
  "torment": "Runeword",
  "torstein's anvil": "Heroic",
  "toxicarcus": "Runeword",
  "trapped vessel": "Runeword",
  "traveler's compass": "Set",
  "traveler's double belt": "Set",
  "traveler's leather jacket": "Set",
  "traveler's map journal": "Set",
  "treasure hunter's boots": "Satanic",
  "treasure pendant": "Satanic",
  "tribal belt": "Satanic",
  "tribal boots": "Satanic",
  "trophy hunter": "Heroic",
  "tropical storm": "Satanic",
  "true aim": "Runeword",
  "tundra hunter's long coat": "Heroic",
  "tundra marchers": "Satanic",
  "tundra warrior's girdle": "Satanic",
  "uabel's chest": "Set",
  "uabel's gloves": "Set",
  "uabel's helmet": "Set",
  "uabel's wand": "Set",
  "ukko's revenge": "Heroic",
  "underworld's skullbreaker": "Satanic",
  "unearthed esoteric panoply": "Satanic",
  "unfathomable puzzle": "Satanic",
  "unholy god's flail": "Satanic",
  "upi's sweetshirt": "Satanic",
  "usb's cord": "Satanic",
  "vagabond's marchers": "Set",
  "vagabond's strap": "Set",
  "vagabond's ward": "Set",
  "vagabond's wraps": "Set",
  "valkyrie": "Runeword",
  "valkyrie's battle raiment": "Set",
  "valkyrie's battle shield": "Set",
  "valkyrie's thunder javelin": "Set",
  "valkyrie's winged helm": "Set",
  "vampire hunter": "Satanic",
  "vanguard's lance": "Satanic",
  "veil of consecration": "Satanic",
  "veil of mystery": "Satanic",
  "venom roamers": "Heroic",
  "venom's necklace": "Set",
  "venom's ribcage": "Set",
  "venom's skull": "Set",
  "venom's talons": "Set",
  "venomburned gauntlets": "Satanic",
  "venomsteel carapace": "Heroic",
  "vigorous lifegrips": "Satanic",
  "viking's glyphed rune": "Satanic",
  "viking's sacred axe": "Set",
  "viking's sacred boots": "Set",
  "viking's sacred helmet": "Set",
  "violence": "Runeword",
  "viper's seal of corrosion": "Satanic",
  "vipermagi's belt": "Satanic",
  "vipermagi's sprinters": "Satanic",
  "virulence": "Runeword",
  "visage of relentless rage": "Satanic",
  "visage's eye": "Satanic",
  "void bomba": "Heroic",
  "voodoo doll": "Set",
  "voodoo magician's skull": "Satanic",
  "voodoo stompers": "Satanic",
  "vorpal sharktooth": "Satanic",
  "wakayka's tomahawk": "Satanic",
  "wall of the legion": "Satanic",
  "war god's lance": "Satanic",
  "warbosses' trophy belt": "Satanic",
  "warbringer": "Satanic",
  "ward of blood": "Satanic",
  "ward of toxicity": "Satanic",
  "wardbreaker armor": "Satanic",
  "wargod's wrath": "Satanic",
  "warlord's fury": "Satanic",
  "warmaster's tribal paws": "Satanic",
  "water melon": "Angelic",
  "wendigo skull": "Set",
  "whisper walker's feiyue": "Satanic",
  "will of thanos": "Runeword",
  "wind guardian's gladius": "Satanic",
  "wind token": "Satanic",
  "wind walker's step": "Heroic",
  "wind's force": "Satanic",
  "windstride": "Runeword",
  "winter's bite": "Heroic",
  "wisdom's hold": "Satanic",
  "witch's wand": "Satanic",
  "witches potion": "Satanic",
  "witches brimmed hat": "Satanic",
  "witches claw": "Satanic",
  "wizard boots": "Satanic",
  "wizard potion": "Satanic",
  "wizard's dice": "Heroic",
  "wormclaw": "Satanic",
  "wraith forged cleaver": "Heroic",
  "wraith's cloak": "Heroic",
  "wraithbone": "Satanic",
  "ymir's freezing boots": "Set",
  "ymir's frozen shroud": "Set",
  "ymir's frozen tear": "Set",
  "ymir's frozen vestment": "Set",
  "yoshi's throat-cutters": "Satanic",
  "zealot's beads of destruction": "Set",
  "zealot's book of prophecy": "Set",
  "zealot's deathbringers": "Set",
  "zealot's guise of doom": "Set",
  "zephy's gown": "Satanic",
  "zeus' battle boots": "Set",
  "zeus' body armor": "Set",
  "zeus' circlet": "Set",
};

export function lookupKnownItemRarity(_type: number, name: string | undefined): KnownItemRarity | null {
  if (!name) return null;
  return ITEM_RARITY_BY_NAME[normalizeItemName(name)] ?? null;
}

function normalizeItemName(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[\u2018\u2019`\u00b4]/g, "'")
    .replace(/[\u201c\u201d]/g, '\"')
    .replace(/[’‘`´]/g, "'")
    .replace(/[“”]/g, '\"')
    .replace(/[\u2010-\u2015]/g, "-")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}
