import type { ItemTranslation } from "./item-lookup";

const STACK_ITEM_TRANSLATIONS: ItemTranslation[] = [
  { localizationId: "stack_basic_key", name: "Basic Key", gameId: 0, type: 12, weaponType: 0 },
  { localizationId: "stack_crystal_key", name: "Crystal Key", gameId: 1, type: 12, weaponType: 0 },
  { localizationId: "stack_bifrost_key", name: "Bifr\u00f6st Key", gameId: 2, type: 12, weaponType: 0 },
  { localizationId: "stack_ruby_key", name: "Ruby Key", gameId: 7, type: 12, weaponType: 0 },
  { localizationId: "stack_curacan_key", name: "Curacan Key", gameId: 31, type: 12, weaponType: 0 },
  { localizationId: "stack_terror_key", name: "Key of Terror", gameId: 5, type: 12, weaponType: 0 },
  { localizationId: "stack_smelly_cheese", name: "Smelly Cheese", gameId: 9, type: 12, weaponType: 0 },
  { localizationId: "stack_cellar_key", name: "Cellar Key", gameId: 10, type: 12, weaponType: 0 },
  { localizationId: "stack_tower_key", name: "Tower Key", gameId: 11, type: 12, weaponType: 0 },
  { localizationId: "stack_frosted_key", name: "Frosted Key", gameId: 12, type: 12, weaponType: 0 },
  { localizationId: "stack_copper_key", name: "Copper Key", gameId: 13, type: 12, weaponType: 0 },
  { localizationId: "stack_mystic_key", name: "Mystic Key", gameId: 14, type: 12, weaponType: 0 },
  { localizationId: "stack_rusted_key", name: "Rusted Key", gameId: 15, type: 12, weaponType: 0 },
  { localizationId: "stack_shovel_key", name: "Shovel Key", gameId: 16, type: 12, weaponType: 0 },
  { localizationId: "stack_ancient_key", name: "Ancient Key", gameId: 17, type: 12, weaponType: 0 },
  { localizationId: "stack_tomb_key", name: "Tomb Key", gameId: 18, type: 12, weaponType: 0 },
  { localizationId: "stack_devils_key", name: "Devil's Key", gameId: 19, type: 12, weaponType: 0 },
  { localizationId: "stack_pickaxe", name: "Pickaxe", gameId: 20, type: 12, weaponType: 0 },
  { localizationId: "stack_battle_key", name: "Battle Key", gameId: 21, type: 12, weaponType: 0 },
  { localizationId: "stack_garden_key", name: "Garden Key", gameId: 22, type: 12, weaponType: 0 },
  { localizationId: "stack_golden_key", name: "Golden Key", gameId: 23, type: 12, weaponType: 0 },
  { localizationId: "stack_axe_key", name: "Axe Key", gameId: 24, type: 12, weaponType: 0 },
  { localizationId: "stack_valor_key", name: "Valor Key", gameId: 25, type: 12, weaponType: 0 },
  { localizationId: "stack_naga_scale_key", name: "Naga Scale Key", gameId: 26, type: 12, weaponType: 0 },
  { localizationId: "stack_magma_key", name: "Magma Key", gameId: 27, type: 12, weaponType: 0 },
  { localizationId: "stack_helflame_torch", name: "Helflame Torch", gameId: 28, type: 12, weaponType: 0 },
  { localizationId: "stack_warp_key", name: "Warp Key", gameId: 29, type: 12, weaponType: 0 },
  { localizationId: "stack_storage_key", name: "Storage Key", gameId: 30, type: 12, weaponType: 0 },
  { localizationId: "stack_chaos_key", name: "Chaos Key", gameId: 33, type: 12, weaponType: 0 },
  { localizationId: "stack_battle_fragment", name: "Battle Fragment", gameId: 0, type: 13, weaponType: 0 },
  { localizationId: "stack_dimensional_shard", name: "Dimensional Shard", gameId: 1, type: 13, weaponType: 0 },
  { localizationId: "stack_gurags_soul", name: "Gurag's Soul", gameId: 2, type: 13, weaponType: 0 },
  { localizationId: "stack_deaths_sigil", name: "Death's Sigil", gameId: 3, type: 13, weaponType: 0 },
  { localizationId: "stack_damiens_eye", name: "Damien's Eye", gameId: 4, type: 13, weaponType: 0 },
  { localizationId: "stack_anubiss_ankh", name: "Anubis's Ankh", gameId: 5, type: 13, weaponType: 0 },
  { localizationId: "stack_karp_kings_bellybutton", name: "Karp King's Bellybutton", gameId: 6, type: 13, weaponType: 0 },
  { localizationId: "stack_satans_horn", name: "Satan's Horn", gameId: 7, type: 13, weaponType: 0 },
  { localizationId: "stack_soul_of_anguish", name: "Soul of Anguish", gameId: 14, type: 13, weaponType: 0 },
  { localizationId: "stack_scroll_of_ra", name: "Scroll of Ra", gameId: 17, type: 13, weaponType: 0 },
  { localizationId: "stack_inf_scroll_of_ra", name: "Infernal Scroll of Ra", gameId: 52, type: 13, weaponType: 0 },
  { localizationId: "stack_colosseum_fragment", name: "Colosseum Fragment", gameId: 18, type: 13, weaponType: 0 },
  { localizationId: "stack_death", name: "Death", gameId: 19, type: 13, weaponType: 0 },
  { localizationId: "stack_the_tower", name: "The Tower", gameId: 20, type: 13, weaponType: 0 },
  { localizationId: "stack_the_fool", name: "The Fool", gameId: 21, type: 13, weaponType: 0 },
  { localizationId: "stack_the_magician_13_22_0", name: "The Magician", gameId: 22, type: 13, weaponType: 0 },
  { localizationId: "stack_the_world", name: "The World", gameId: 23, type: 13, weaponType: 0 },
  { localizationId: "stack_the_wheel_of_fortune", name: "The Wheel of Fortune", gameId: 24, type: 13, weaponType: 0 },
  { localizationId: "stack_the_high_priestess", name: "The High Priestess", gameId: 25, type: 13, weaponType: 0 },
  { localizationId: "stack_the_empress", name: "The Empress", gameId: 26, type: 13, weaponType: 0 },
  { localizationId: "stack_the_emperor", name: "The Emperor", gameId: 27, type: 13, weaponType: 0 },
  { localizationId: "stack_the_chariot", name: "The Chariot", gameId: 28, type: 13, weaponType: 0 },
  { localizationId: "stack_the_lovers", name: "The Lovers", gameId: 29, type: 13, weaponType: 0 },
  { localizationId: "stack_justice", name: "Justice", gameId: 30, type: 13, weaponType: 0 },
  { localizationId: "stack_the_hermit", name: "The Hermit", gameId: 31, type: 13, weaponType: 0 },
  { localizationId: "stack_temperance", name: "Temperance", gameId: 32, type: 13, weaponType: 0 },
  { localizationId: "stack_the_devil", name: "The Devil", gameId: 33, type: 13, weaponType: 0 },
  { localizationId: "stack_the_moon", name: "The Moon", gameId: 34, type: 13, weaponType: 0 },
  { localizationId: "stack_the_sun", name: "The Sun", gameId: 35, type: 13, weaponType: 0 },
  { localizationId: "stack_the_star", name: "The Star", gameId: 36, type: 13, weaponType: 0 },
  { localizationId: "stack_judgement", name: "Judgement", gameId: 37, type: 13, weaponType: 0 },
  { localizationId: "stack_strength", name: "Strength", gameId: 38, type: 13, weaponType: 0 },
  { localizationId: "stack_the_hanged_man", name: "The Hanged Man", gameId: 39, type: 13, weaponType: 0 },
  { localizationId: "stack_the_hierophant", name: "The Hierophant", gameId: 40, type: 13, weaponType: 0 },
  { localizationId: "stack_damiens_infernal_eye", name: "Damien's Infernal Eye", gameId: 45, type: 13, weaponType: 0 },
  { localizationId: "stack_satans_infernal_horn", name: "Satan's Infernal Horn", gameId: 48, type: 13, weaponType: 0 },
  { localizationId: "stack_soul_of_infernal_anguish", name: "Soul of Infernal Anguish", gameId: 49, type: 13, weaponType: 0 },
  { localizationId: "stack_soul_of_infernal_despair", name: "Soul of Infernal Despair", gameId: 50, type: 13, weaponType: 0 },
  { localizationId: "stack_soul_of_infernal_corruption", name: "Soul of Infernal Corruption", gameId: 51, type: 13, weaponType: 0 },
  { localizationId: "stack_fragment_of_nightmare", name: "Fragment of Nightmare", gameId: 61, type: 13, weaponType: 0 },
  { localizationId: "stack_fragment_of_time", name: "Fragment of Time", gameId: 64, type: 13, weaponType: 0 },
  { localizationId: "stack_bloodstone", name: "Bloodstone", gameId: 0, type: 14, weaponType: 0 },
  { localizationId: "stack_snake_tooth", name: "Snake Tooth", gameId: 1, type: 14, weaponType: 0 },
  { localizationId: "stack_copperstone", name: "Copperstone", gameId: 2, type: 14, weaponType: 0 },
  { localizationId: "stack_liquate", name: "Liquate", gameId: 3, type: 14, weaponType: 0 },
  { localizationId: "stack_darkstone", name: "Darkstone", gameId: 4, type: 14, weaponType: 0 },
  { localizationId: "stack_lesser_impstone", name: "Lesser Impstone", gameId: 5, type: 14, weaponType: 0 },
  { localizationId: "stack_iron_opal", name: "Iron Opal", gameId: 6, type: 14, weaponType: 0 },
  { localizationId: "stack_shadow_stone", name: "Shadow Stone", gameId: 7, type: 14, weaponType: 0 },
  { localizationId: "stack_twilight_citrine", name: "Twilight Citrine", gameId: 8, type: 14, weaponType: 0 },
  { localizationId: "stack_ocean_agate", name: "Ocean Agate", gameId: 9, type: 14, weaponType: 0 },
  { localizationId: "stack_greater_impstone", name: "Greater Impstone", gameId: 10, type: 14, weaponType: 0 },
  { localizationId: "stack_huge_spessarite", name: "Huge Spessarite", gameId: 11, type: 14, weaponType: 0 },
  { localizationId: "stack_flaming_core", name: "Flaming Core", gameId: 13, type: 14, weaponType: 0 },
  { localizationId: "stack_demon_tooth", name: "Demon Tooth", gameId: 14, type: 14, weaponType: 0 },
  { localizationId: "stack_ketamineral", name: "Ketamineral", gameId: 15, type: 14, weaponType: 0 },
  { localizationId: "stack_jadenium_powder", name: "Jadenium Powder", gameId: 16, type: 14, weaponType: 0 },
  { localizationId: "stack_satans_nail", name: "Satan's Nail", gameId: 17, type: 14, weaponType: 0 },
  { localizationId: "stack_inferno_stone", name: "Inferno Stone", gameId: 18, type: 14, weaponType: 0 },
  { localizationId: "stack_hellstar", name: "Hellstar", gameId: 19, type: 14, weaponType: 0 },
  { localizationId: "stack_tarethium_core", name: "Tarethium Core", gameId: 20, type: 14, weaponType: 0 },
  { localizationId: "stack_dark_matter", name: "Dark Matter", gameId: 21, type: 14, weaponType: 0 },
  { localizationId: "stack_demon_soulstone", name: "Demon Soulstone", gameId: 22, type: 14, weaponType: 0 },
  { localizationId: "stack_storm_opal", name: "Storm Opal", gameId: 23, type: 14, weaponType: 0 },
  { localizationId: "stack_copper_ore", name: "Copper Ore", gameId: 27, type: 14, weaponType: 0 },
  { localizationId: "stack_iron_ore", name: "Iron Ore", gameId: 28, type: 14, weaponType: 0 },
  { localizationId: "stack_gold_ore", name: "Gold Ore", gameId: 29, type: 14, weaponType: 0 },
  { localizationId: "stack_ruby", name: "Ruby", gameId: 30, type: 14, weaponType: 0 },
  { localizationId: "stack_jade", name: "Jade", gameId: 31, type: 14, weaponType: 0 },
  { localizationId: "stack_tarethium_ore", name: "Tarethium Ore", gameId: 32, type: 14, weaponType: 0 },
  { localizationId: "stack_flawed_amethyst", name: "Flawed Amethyst", gameId: 35, type: 14, weaponType: 0 },
  { localizationId: "stack_jussis_bong", name: "Jussi's Bong", gameId: 40, type: 14, weaponType: 0 },
  { localizationId: "stack_sheep_pelt", name: "Sheep Pelt", gameId: 41, type: 14, weaponType: 0 },
  { localizationId: "stack_satanic_dice", name: "Satanic Dice", gameId: 43, type: 14, weaponType: 0 },
  { localizationId: "stack_unstable_dust", name: "Unstable Dust", gameId: 50, type: 14, weaponType: 0 },
  { localizationId: "stack_greater_unstable_dust", name: "Greater Unstable Dust", gameId: 51, type: 14, weaponType: 0 },
  { localizationId: "stack_satanic_crystal_fragment", name: "Satanic Crystal Fragment", gameId: 60, type: 14, weaponType: 0 },
  { localizationId: "stack_prophets_wisdom", name: "Prophet's Wisdom", gameId: 62, type: 14, weaponType: 0 },
  { localizationId: "stack_gypsys_prophecy", name: "Gypsy's Prophecy", gameId: 63, type: 14, weaponType: 0 },
  { localizationId: "stack_destiny_shard", name: "Destiny Shard", gameId: 64, type: 14, weaponType: 0 },
  { localizationId: "stack_blacksmiths_mallet", name: "Blacksmith's Mallet", gameId: 65, type: 14, weaponType: 0 },
  { localizationId: "stack_destiny_shard_fragment", name: "Destiny Shard Fragment", gameId: 66, type: 14, weaponType: 0 },
  { localizationId: "stack_ol_rune", name: "Ol Rune", gameId: 1, type: 15, weaponType: 0 },
  { localizationId: "stack_old_rune", name: "Old Rune", gameId: 2, type: 15, weaponType: 0 },
  { localizationId: "stack_tor_rune", name: "Tor Rune", gameId: 3, type: 15, weaponType: 0 },
  { localizationId: "stack_naf_rune", name: "Naf Rune", gameId: 4, type: 15, weaponType: 0 },
  { localizationId: "stack_eth_rune", name: "Eth Rune", gameId: 5, type: 15, weaponType: 0 },
  { localizationId: "stack_uth_rune", name: "Uth Rune", gameId: 6, type: 15, weaponType: 0 },
  { localizationId: "stack_tul_rune", name: "Tul Rune", gameId: 7, type: 15, weaponType: 0 },
  { localizationId: "stack_rex_rune", name: "Rex Rune", gameId: 8, type: 15, weaponType: 0 },
  { localizationId: "stack_ert_rune", name: "Ert Rune", gameId: 9, type: 15, weaponType: 0 },
  { localizationId: "stack_thal_rune", name: "Thal Rune", gameId: 10, type: 15, weaponType: 0 },
  { localizationId: "stack_ymn_rune", name: "Ymn Rune", gameId: 11, type: 15, weaponType: 0 },
  { localizationId: "stack_sal_rune", name: "Sal Rune", gameId: 12, type: 15, weaponType: 0 },
  { localizationId: "stack_nut_rune", name: "Nut Rune", gameId: 13, type: 15, weaponType: 0 },
  { localizationId: "stack_del_rune", name: "Del Rune", gameId: 14, type: 15, weaponType: 0 },
  { localizationId: "stack_hel_rune", name: "Hel Rune", gameId: 15, type: 15, weaponType: 0 },
  { localizationId: "stack_io_rune", name: "Io Rune", gameId: 16, type: 15, weaponType: 0 },
  { localizationId: "stack_lum_rune", name: "Lum Rune", gameId: 17, type: 15, weaponType: 0 },
  { localizationId: "stack_co_rune", name: "Co Rune", gameId: 18, type: 15, weaponType: 0 },
  { localizationId: "stack_fel_rune", name: "Fel Rune", gameId: 19, type: 15, weaponType: 0 },
  { localizationId: "stack_lem_rune", name: "Lem Rune", gameId: 20, type: 15, weaponType: 0 },
  { localizationId: "stack_pul_rune", name: "Pul Rune", gameId: 21, type: 15, weaponType: 0 },
  { localizationId: "stack_um_rune", name: "Um Rune", gameId: 22, type: 15, weaponType: 0 },
  { localizationId: "stack_mal_rune", name: "Mal Rune", gameId: 23, type: 15, weaponType: 0 },
  { localizationId: "stack_ist_rune", name: "Ist Rune", gameId: 24, type: 15, weaponType: 0 },
  { localizationId: "stack_gul_rune", name: "Gul Rune", gameId: 25, type: 15, weaponType: 0 },
  { localizationId: "stack_vex_rune", name: "Vex Rune", gameId: 26, type: 15, weaponType: 0 },
  { localizationId: "stack_qi_rune", name: "Qi Rune", gameId: 27, type: 15, weaponType: 0 },
  { localizationId: "stack_xo_rune", name: "Xo Rune", gameId: 28, type: 15, weaponType: 0 },
  { localizationId: "stack_sur_rune", name: "Sur Rune", gameId: 29, type: 15, weaponType: 0 },
  { localizationId: "stack_ber_rune", name: "Ber Rune", gameId: 30, type: 15, weaponType: 0 },
  { localizationId: "stack_jah_rune", name: "Jah Rune", gameId: 31, type: 15, weaponType: 0 },
  { localizationId: "stack_drax_rune", name: "Drax Rune", gameId: 32, type: 15, weaponType: 0 },
  { localizationId: "stack_zed_rune", name: "Zed Rune", gameId: 33, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_amethyst", name: "Chipped Amethyst", gameId: 34, type: 15, weaponType: 0 },
  { localizationId: "stack_socket_flawed_amethyst", name: "Flawed Amethyst", gameId: 35, type: 15, weaponType: 0 },
  { localizationId: "stack_amethyst", name: "Amethyst", gameId: 36, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_amethyst", name: "Flawless Amethyst", gameId: 37, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_amethyst", name: "Perfect Amethyst", gameId: 38, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_emerald", name: "Chipped Emerald", gameId: 40, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_emerald", name: "Flawed Emerald", gameId: 41, type: 15, weaponType: 0 },
  { localizationId: "stack_emerald", name: "Emerald", gameId: 42, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_emerald", name: "Flawless Emerald", gameId: 43, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_emerald", name: "Perfect Emerald", gameId: 44, type: 15, weaponType: 0 },
  { localizationId: "stack_pristine_emerald", name: "Pristine Emerald", gameId: 45, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_ruby", name: "Chipped Ruby", gameId: 46, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_ruby", name: "Flawed Ruby", gameId: 47, type: 15, weaponType: 0 },
  { localizationId: "stack_socket_ruby", name: "Ruby", gameId: 48, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_ruby", name: "Flawless Ruby", gameId: 49, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_ruby", name: "Perfect Ruby", gameId: 50, type: 15, weaponType: 0 },
  { localizationId: "stack_pristine_ruby", name: "Pristine Ruby", gameId: 51, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_sapphire", name: "Chipped Sapphire", gameId: 52, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_sapphire", name: "Flawed Sapphire", gameId: 53, type: 15, weaponType: 0 },
  { localizationId: "stack_sapphire", name: "Sapphire", gameId: 54, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_sapphire", name: "Flawless Sapphire", gameId: 55, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_sapphire", name: "Perfect Sapphire", gameId: 56, type: 15, weaponType: 0 },
  { localizationId: "stack_pristine_sapphire", name: "Pristine Sapphire", gameId: 57, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_skull", name: "Chipped Skull", gameId: 58, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_skull", name: "Flawed Skull", gameId: 59, type: 15, weaponType: 0 },
  { localizationId: "stack_skull", name: "Skull", gameId: 60, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_skull", name: "Flawless Skull", gameId: 61, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_skull", name: "Perfect Skull", gameId: 62, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_topaz", name: "Chipped Topaz", gameId: 64, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_topaz", name: "Flawed Topaz", gameId: 65, type: 15, weaponType: 0 },
  { localizationId: "stack_topaz", name: "Topaz", gameId: 66, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_topaz", name: "Flawless Topaz", gameId: 67, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_topaz", name: "Perfect Topaz", gameId: 68, type: 15, weaponType: 0 },
  { localizationId: "stack_uncut_jewel_of_platoon", name: "Uncut Jewel of Platoon", gameId: 111, type: 15, weaponType: 0 },
  { localizationId: "stack_goblin", name: "Goblin", gameId: 112, type: 15, weaponType: 0 },
  { localizationId: "stack_runeforge", name: "Runeforge", gameId: 113, type: 15, weaponType: 0 },
  { localizationId: "stack_kobold", name: "Kobold", gameId: 114, type: 15, weaponType: 0 },
  { localizationId: "stack_heroism", name: "Heroism", gameId: 115, type: 15, weaponType: 0 },
  { localizationId: "stack_angel", name: "Angel", gameId: 116, type: 15, weaponType: 0 },
  { localizationId: "stack_swiftness", name: "Swiftness", gameId: 117, type: 15, weaponType: 0 },
  { localizationId: "stack_agility", name: "Agility", gameId: 118, type: 15, weaponType: 0 },
  { localizationId: "stack_magister", name: "Magister", gameId: 119, type: 15, weaponType: 0 },
  { localizationId: "stack_brute", name: "Brute", gameId: 120, type: 15, weaponType: 0 },
  { localizationId: "stack_wisdom", name: "Wisdom", gameId: 121, type: 15, weaponType: 0 },
  { localizationId: "stack_relic", name: "Relic", gameId: 122, type: 15, weaponType: 0 },
  { localizationId: "stack_treasure", name: "Treasure", gameId: 123, type: 15, weaponType: 0 },
  { localizationId: "stack_midas", name: "Midas", gameId: 124, type: 15, weaponType: 0 },
  { localizationId: "stack_gladiator", name: "Gladiator", gameId: 125, type: 15, weaponType: 0 },
  { localizationId: "stack_doom", name: "Doom", gameId: 127, type: 15, weaponType: 0 },
  { localizationId: "stack_fatality", name: "Fatality", gameId: 128, type: 15, weaponType: 0 },
  { localizationId: "stack_ancient", name: "Ancient", gameId: 129, type: 15, weaponType: 0 },
  { localizationId: "stack_chipped_diamond", name: "Chipped Diamond", gameId: 130, type: 15, weaponType: 0 },
  { localizationId: "stack_flawed_diamond", name: "Flawed Diamond", gameId: 131, type: 15, weaponType: 0 },
  { localizationId: "stack_diamond", name: "Diamond", gameId: 132, type: 15, weaponType: 0 },
  { localizationId: "stack_flawless_diamond", name: "Flawless Diamond", gameId: 133, type: 15, weaponType: 0 },
  { localizationId: "stack_perfect_diamond", name: "Perfect Diamond", gameId: 134, type: 15, weaponType: 0 },  
  { localizationId: "stack_inf_colosseum_fragment", name: "Infernal Colosseum Fragment", gameId: 53, type: 13, weaponType: 0 },
  { localizationId: "stack_inf_dimensional_shard", name: "Infernal Dimensional Shard", gameId: 42, type: 13, weaponType: 0 },
  { localizationId: "stack_inf_battle_fragment", name: "Infernal Battle Fragment", gameId: 41, type: 13, weaponType: 0 },
  { localizationId: "stack_blessed_dice", name: "Blessed Dice", gameId: 67, type: 14, weaponType: 0 },
  { localizationId: "stack_tinkerers_toolkit", name: "Tinkerer's Toolkit", gameId: 52, type: 14, weaponType: 0 },
];

const stackLookup = new Map(STACK_ITEM_TRANSLATIONS.map((item) => [`${item.type}:${item.gameId}`, item]));

export function lookupStackItemTranslation(type: number, gameId: number): ItemTranslation | null {
  return stackLookup.get(`${type}:${gameId}`) ?? null;
}

export function allStackItemTranslations(): ItemTranslation[] {
  return [...STACK_ITEM_TRANSLATIONS];
}
